import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'secondary': '#5c5f60',
        'surface-dim': '#dadada',
        'tertiary-container': '#696868',
        'on-primary-fixed': '#001550',
        'surface-variant': '#e2e2e2',
        'on-background': '#1a1c1c',
        'surface-bright': '#f9f9f9',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#626566',
        'surface': '#f9f9f9',
        'on-primary-container': '#e5e8ff',
        'primary': '#0043c8',
        'error-container': '#ffdad6',
        'outline': '#737688',
        'primary-container': '#0057ff',
        'inverse-primary': '#b6c4ff',
        'primary-fixed-dim': '#b6c4ff',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'on-secondary-fixed': '#191c1d',
        'tertiary-fixed-dim': '#c8c6c5',
        'surface-container-highest': '#e2e2e2',
        'surface-tint': '#004ee7',
        'primary-fixed': '#dce1ff',
        'on-tertiary-fixed-variant': '#474746',
        'secondary-fixed': '#e1e3e4',
        'on-secondary-fixed-variant': '#454748',
        'outline-variant': '#c3c5d9',
        'on-tertiary-fixed': '#1c1b1b',
        'secondary-container': '#e1e3e4',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary': '#ffffff',
        'background': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#515050',
        'on-tertiary-container': '#ebe8e8',
        'on-primary-fixed-variant': '#003ab2',
        'surface-container-low': '#f4f3f3',
        'on-surface': '#1a1c1c',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#c5c7c8',
        'inverse-surface': '#2f3131',
        'on-surface-variant': '#434656',
        'inverse-on-surface': '#f1f1f1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'jarak-sedang': '32px',
        'jarak-kecil': '16px',
        'jarak-mikro': '4px',
        'satuan-dasar': '8px',
        'jarak-besar': '64px',
        'jarak-ekstra': '128px',
        'gutter-grid': '24px',
        'margin-kontainer': '80px',
      },
      fontFamily: {
        'judul-ekstra-besar': ['Noto Serif', 'serif'],
        'keterangan-kecil': ['Inter', 'sans-serif'],
        'paragraf-utama': ['Inter', 'sans-serif'],
        'subjudul-arsitektur': ['Noto Serif', 'serif'],
        'label-tombol': ['Inter', 'sans-serif'],
        'judul-halaman': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'judul-ekstra-besar': [
          '64px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'keterangan-kecil': [
          '12px',
          { lineHeight: '1.5', fontWeight: '400' },
        ],
        'paragraf-utama': [
          '16px',
          { lineHeight: '1.6', fontWeight: '400' },
        ],
        'subjudul-arsitektur': [
          '24px',
          { lineHeight: '1.4', fontWeight: '400' },
        ],
        'label-tombol': [
          '14px',
          { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'judul-halaman': [
          '48px',
          { lineHeight: '1.2', fontWeight: '600' },
        ],
      },
      animation: {
        'fade-in': 'fade-in 0.6s ease-out',
        'slide-up': 'slide-up 0.6s ease-out',
        'scale-in': 'scale-in 0.5s ease-out',
        'slide-in-left': 'slide-in-left 0.6s ease-out',
        'slide-in-right': 'slide-in-right 0.6s ease-out',
      },
    },
  },
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
} satisfies Config;
